$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$bibtex_use = 2;
$clean_ext = 'bbl blg run.xml synctex.gz fdb_latexmk fls out toc lof lot aux log';
